version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/store-2
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/before-deploy.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/after-deploy.sh
      timeout: 180
      runas: ubuntu
